name: Health check

on:
  workflow_dispatch:
  schedule:
    - cron: "30 * * * *"

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check server healthy
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://full-stack-open-pokedex-drx2.onrender.com/health
